# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: laravel
  - before: alias sail='[ -f sail ] && bash sail || bash vendor/bin/sail'
  - init: >
      composer install &&
      vendor/bin/sail up -d &&
      vendor/bin/sail npm install &&
      npm run dev &&
      vendor/bin/sail artisan key:generate &&
      gp sync-done laravel
    command: vendor/bin/sail up -d
  
  - name: mix
  - command: gp sync-await laravel && npx mix watch

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8080
    onOpen: open-preview
