# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: >
      composer install &&
      cp .env.example .env &&
      APP_PORT=8080 vendor/bin/sail up -d &&
      vendor/bin/sail npm install &&
      npx mix &&
      vendor/bin/sail artisan key:generate &&
      vendor/bin/sail artisan migrate --seed
    command: APP_PORT=8080 vendor/bin/sail up -d

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8080
    onOpen: open-preview
